# Generated by Django 4.1.2 on 2022-11-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('account', '0003_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
